# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WK5au66lEbIXXzPTeS22wbVgvWMlRsB9
"""

import numpy as np
import matplotlib.pyplot as plt


y = np.linspace(-5,5,100)
x=(y*y)
plt.plot(x,y,label='$y^2=8x$')
plt.xlabel('$x-axis$')
plt.ylabel('$y-axis$')

def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB 

#plotting focus
plt.plot(2,0,'o',label='$focus$')
plt.text(2,0,'F(2,0)')
plt.plot(0,0,'o',label='vertex')
plt.text(0,0,' V(0,0)')


plt.legend(loc='best')
plt.grid()
plt.xlim([-3,5])
plt.ylim([-6,6])